name: glady
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shimmer:
  url_launcher: ^6.3.1
  pin_code_fields:
  shadify: ^1.0.1
  loading_animation_widget:
  http_parser: ^4.0.2
  mime: ^1.0.4
  flutter_screenutil: ^5.9.3
  flutter_animate:
  get:
  google_sign_in: ^6.3.0
  get_storage:
  connectivity_plus:
  flutter_svg:
  intl:
  cached_network_image:
  country_picker: ^2.0.27
  webview_flutter: ^4.13.0
  pinput: ^5.0.2
  google_fonts:
  image_picker: ^1.2.1
  socket_io_client: ^3.1.3
  dio: ^5.4.0
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.0.1



dev_dependencies:
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.5
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  flutter_gen_runner:
  
  # dart run rename_app:main all="My App Name"
  # flutter pub run change_app_package_name:main com.clint_name.app_Name

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/dummy/
